8.3 compat/string to array
FriendsOfSymfony1/symfony1 pull request #298
Opened 2023-12-27 16:28 UTC by iricketson

Symfony helpers such as `link_to_if`, [set missing variables to `null`](https://github.com/FriendsOfSymfony1/symfony1/blob/2a6803324c48c9edc1a9f19f563e5235dc39f44b/lib/helper/UrlHelper.php#L221), and then [send those null values to `_parse_attributes`](https://github.com/FriendsOfSymfony1/symfony1/blob/2a6803324c48c9edc1a9f19f563e5235dc39f44b/lib/helper/TagHelper.php#L116), which in turn causes a deprecation notice when [`sfToolkit::stringToArray` calls `preg_match_all`](https://github.com/FriendsOfSymfony1/symfony1/blob/2a6803324c48c9edc1a9f19f563e5235dc39f44b/lib/util/sfToolkit.class.php#L257) and the `$subject` variable is null ([it requires a string](https://www.php.net/preg_match_all)).  

> Deprecated: preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated in /path/to/friendsofsymfony1/symfony1/lib/util/sfToolkit.class.php on line 276

This PR simply ensures that the string variable is actually a string when passed to `preg_match_all`.

2023-12-27 16:32 UTC, alquerci approved these changes

2023-12-27 16:37 UTC, alquerci requested changes

2023-12-27 16:37 UTC, alquerci commented on test/unit/util/sfToolkitTest.php
> +    null => array(),
This `null` index is converted to an empty string.

So, need to think to test in different way.

2023-12-27 16:48 UTC, alquerci commented
Moreover, this deprecation is since PHP 8.1.

Nice catch.

2023-12-27 17:34 UTC, alquerci approved these changes

2023-12-27 18:48 UTC, thirsch approved these changes

2023-12-29 10:06 UTC, mentalstring approved these changes

2023-12-30 21:24 UTC, thePanz approved these changes

2023-12-30 21:26 UTC, merged

2023-12-30 21:28 UTC, thePanz commented
Thanks @iricketson for the PR, I rebased your branch and re-worded the commits. Now merged!

Thanks @alquerci @mentalstring and @thirsch for reviewing!